// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Cart struct {
	ID int32
}

type CartItem struct {
	ID      int32
	CartID  int64
	Product string
	Price   int64
}
