// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const addToCart = `-- name: AddToCart :one
INSERT INTO cart_items (cart_id, product, price)
VALUES ($1, $2, $3)
RETURNING id
`

type AddToCartParams struct {
	CartID  int64
	Product string
	Price   int64
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) (int32, error) {
	row := q.db.QueryRow(ctx, addToCart, arg.CartID, arg.Product, arg.Price)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts DEFAULT VALUES
RETURNING id
`

func (q *Queries) CreateCart(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, createCart)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts
WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCart, id)
	return err
}

const removeFromCart = `-- name: RemoveFromCart :exec
DELETE FROM cart_items
WHERE id = $1
`

func (q *Queries) RemoveFromCart(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, removeFromCart, id)
	return err
}

const updateCartItem = `-- name: UpdateCartItem :one
UPDATE cart_items
SET product = $2, price = $3
WHERE id = $1
RETURNING id
`

type UpdateCartItemParams struct {
	ID      int32
	Product string
	Price   int64
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateCartItem, arg.ID, arg.Product, arg.Price)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const viewCart = `-- name: ViewCart :many
SELECT id, cart_id, product, price
FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) ViewCart(ctx context.Context, cartID int64) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, viewCart, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.Product,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
